runtime: python37
entrypoint: gunicorn -b :$PORT ingestapp:app --timeout 120
service: flights
manual_scaling:
  instances: 1

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: cloud-training-demos-ml
#[END env]

handlers:
- url: /ingest
  script: auto

- url: /.*
  script: auto
